credentials:
  usernames:
    isa:
      email: isa@nitiip.com
      name: Bos Isa
      # Ini adalah hash rahasia dari password "admin123"
      password: $2b$12$ULIVMDbV2OVBJXVDNaQkEe/OcpcrGhhqmOkCL/DfE.yyoPJb62nXq
cookie:
  expiry_days: 30
  key: kunci_rahasia_otak_kedua_123
  name: otak_kedua_cookie
preauthorized:
  emails:
  - isa@nitiip.com